
spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #JDBC 配置
      url: jdbc:mysql://192.168.0.187:3306/wisdom_cqzt?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: changzx
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      #打开PSCache，并且指定每个连接上PSCache的大小;如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false
      pool-prepared-statements: true
      #指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
      max-open-prepared-statements: 100
      #用来检测连接是否有效的sql，要求是一个查询语句。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: select 'x' FROM DUAL
      #取得对象时是否进行验证，检查对象是否有效
      test-on-borrow: false
      #返回对象时是否进行验证
      test-on-return: false
      #空闲时是否进行验证，检查对象是否有效
      test-while-idle: true
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #监控统计用的filter:stat日;志用的filter:log4j;防御sql注入的filter:wall

netty:
  http:
    port: 9090
